import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { draftMode } from "next/headers";
import "./globals.css";
import { DraftModeBanner } from "./draft-mode-banner";
import { LivePreviewProvider } from "./live-preview-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Wraps every page in the app. Two things here are specific to live preview:
 *
 *   - `draftMode()` is checked once, here, and its result (`isEnabled`) is
 *     passed down to `LivePreviewProvider` so the Contentful SDK only turns
 *     on for someone actually in preview, never for a regular visitor.
 *   - `DraftModeBanner` is rendered unconditionally; it decides on its own
 *     whether to actually show anything.
 */
export default async function RootLayout({ children }: { children: ReactNode }) {
  const { isEnabled } = await draftMode();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LivePreviewProvider enabled={isEnabled}>
          <DraftModeBanner />
          {children}
        </LivePreviewProvider>
      </body>
    </html>
  );
}
