import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { draftMode } from "next/headers";
// @ts-expect-error CSS files are handled by Next.js at runtime.
import "./globals.css";
import { ContentSourceMapsBanner } from "./content-source-maps-banner";
import { DraftModeBanner } from "./draft-mode-banner";
import { LivePreviewProvider } from "./live-preview-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const { isEnabled } = await draftMode();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LivePreviewProvider enabled={isEnabled}>
          <ContentSourceMapsBanner />
          <DraftModeBanner />
          {children}
        </LivePreviewProvider>
      </body>
    </html>
  );
}
